version: '3.7'

services:

  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000